trigger:
  branches:
    include:
    - '*'
    exclude:
    - master
pr:
- master

variables:
  # https://github.com/rust-lang/rust/commit/489b7e4123f9f85d45335d81f21625d08aa87e1f
  CFG_RELEASE_CHANNEL: nightly
  CFG_RELEASE: nightly
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: 1
  RLS_TEST_WAIT_FOR_AGES: 1

jobs:
# Check formatting
- template: ci/azure-rustfmt.yml
  parameters:
    rust: nightly-2019-08-01 # Use last well-known available nightly
    name: rustfmt
    crates:
      rls-analysis: []
      rls-data: []
      rls-rustc: []
      rls-span: []
      rls-vfs: []
      ".": []

# Run unit and integration tests
- template: ci/azure-test.yml
  parameters:
    rust: nightly
    name: tests
    crates:
      rls-analysis: []
      rls-data: []
      rls-rustc: []
      rls-span: []
      rls-vfs: []
      ".":
        - test_name: test_tooltip_std
          test_args: --ignored
      # Test that we don't regress in-process compilation build
        - args: --no-default-features
