[package]
authors = ["The Rust Project Developers"]
name = "rustc_parse_format"
version = "0.0.0"
edition = "2018"

[dependencies]
rustc_span = { path = "../rustc_span" }
rustc_lexer = { path = "../rustc_lexer" }
