[workspace]
members = [ "crates/*", "xtask/" ]

[profile.dev]
# Disabling debug info speeds up builds a bunch,
# and we don't rely on it for debugging that much.
debug = 0

[profile.dev.package]
# These speed up local tests.
rowan.opt-level = 3
rustc-hash.opt-level = 3
smol_str.opt-level = 3
text-size.opt-level = 3
# This speeds up `cargo xtask dist`.
miniz_oxide.opt-level = 3

[profile.release]
incremental = true
debug = 0 # Set this to 1 or 2 to get more useful backtraces in debugger.

# Ideally, we would use `build-override` here, but some crates are also
# needed at run-time and we end up compiling them twice.
[profile.release.package]
chalk-derive.opt-level = 0
proc-macro2.opt-level = 0
quote.opt-level = 0
salsa-macros.opt-level = 0
serde_derive.opt-level = 0
syn.opt-level = 0
tracing-attributes.opt-level = 0
xtask.opt-level = 0

[patch.'crates-io']
# rowan = { path = "../rowan" }

[patch.'https://github.com/rust-lang/chalk.git']
# chalk-solve = { path = "../chalk/chalk-solve" }
# chalk-rust-ir = { path = "../chalk/chalk-rust-ir" }
# chalk-ir = { path = "../chalk/chalk-ir" }
