[package]
name = "rustc-std-workspace-mpk"
version = "1.0"
authors = ["Kayondo Martin <kayondo@snu.ac.kr>"]
license = ''
description = """
Hack for the compiler's own build system
"""

[lib]
path = "lib.rs"

[dependencies]
mpk = { path = "../mpk" }
