[package]
name = "test_utils"
version = "0.0.0"
description = "TBD"
license = "MIT OR Apache-2.0"
authors = ["rust-analyzer developers"]
edition = "2018"

[lib]
doctest = false

[dependencies]
# Avoid adding deps here, this crate is widely used in tests it should compile fast!
difference = "2.0.0"
text-size = "1.0.0"
serde_json = "1.0.48"
rustc-hash = "1.1.0"

stdx = { path = "../stdx", version = "0.0.0" }
