[package]
name = "clippy_dev"
version = "0.0.1"
authors = ["Philipp Hansch <dev@phansch.net>"]
edition = "2018"

[dependencies]
bytecount = "0.6"
clap = "2.33"
itertools = "0.9"
opener = "0.4"
regex = "1"
shell-escape = "0.1"
walkdir = "2"

[features]
deny-warnings = []
