name: linux
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: (${{ matrix.target }}, ${{ matrix.channel }}, ${{ matrix.cfg-release-channel }})
    strategy:
      # https://help.github.com/en/actions/getting-started-with-github-actions/about-github-actions#usage-limits
      # There's a limit of 60 concurrent jobs across all repos in the rust-lang organization.
      # In order to prevent overusing too much of that 60 limit, we throttle the
      # number of rustfmt jobs that will run concurrently.
      max-parallel: 1
      fail-fast: false
      matrix:
        target: [
          x86_64-unknown-linux-gnu,
        ]
        channel: [ nightly ]
        cfg-release-channel: [
          beta,
          nightly,
        ]

    env:
      CFG_RELEASE_CHANNEL: ${{ matrix.cfg-release-channel }}
      CFG_RELEASE: ${{ matrix.cfg-release-channel }}

    steps:
    - name: checkout
      uses: actions/checkout@v2

      # Run build
    - name: setup
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.channel }}-${{ matrix.target }}
        target: ${{ matrix.target }}
        override: true
        profile: minimal
        default: true

    - name: build
      run: |
        rustc -Vv
        cargo -V
        cargo build

    - name: test
      run: cargo test
