name: mac
on: [push, pull_request]

jobs:
  test:
    # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/virtual-environments-for-github-hosted-runners#supported-runners-and-hardware-resources
    # macOS Catalina 10.15
    runs-on: macos-latest
    name: (${{ matrix.target }}, ${{ matrix.channel }})
    strategy:
      fail-fast: false
      matrix:
        target: [
          x86_64-apple-darwin,
        ]
        channel: [ nightly ]

    env:
      CFG_RELEASE_CHANNEL: nightly
      CFG_RELEASE: nightly

    steps:
    - name: checkout
      uses: actions/checkout@v2

      # Run build
    - name: setup
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.channel }}-${{ matrix.target }}
        target: ${{ matrix.target }}
        override: true
        profile: minimal
        default: true

    - name: build
      run: |
        rustc -Vv
        cargo -V
        cargo build

    - name: test
      run: cargo test
