[package]
authors = ["The Rust Project Developers"]
name = "rustc_span"
version = "0.0.0"
edition = "2018"

[lib]
doctest = false

[dependencies]
rustc_serialize = { path = "../rustc_serialize" }
rustc_macros = { path = "../rustc_macros" }
rustc_data_structures = { path = "../rustc_data_structures" }
rustc_index = { path = "../rustc_index" }
rustc_arena = { path = "../rustc_arena" }
scoped-tls = "1.0"
unicode-width = "0.1.4"
cfg-if = "0.1.2"
tracing = "0.1"
sha-1 = "0.9"
sha2 = "0.9"
md-5 = "0.9"
