[package]
name = "base_db"
version = "0.0.0"
description = "TBD"
license = "MIT OR Apache-2.0"
authors = ["rust-analyzer developers"]
edition = "2018"

[lib]
doctest = false

[dependencies]
salsa = "0.15.2"
rustc-hash = "1.1.0"

syntax = { path = "../syntax", version = "0.0.0" }
cfg = { path = "../cfg", version = "0.0.0" }
profile = { path = "../profile", version = "0.0.0" }
tt = { path = "../tt", version = "0.0.0" }
test_utils = { path = "../test_utils", version = "0.0.0" }
vfs = { path = "../vfs", version = "0.0.0" }
stdx = { path = "../stdx", version = "0.0.0" }
