[package]
name = "profile"
version = "0.0.0"
description = "TBD"
license = "MIT OR Apache-2.0"
authors = ["rust-analyzer developers"]
edition = "2018"

[lib]
doctest = false

[dependencies]
once_cell = "1.3.1"
cfg-if = "0.1.10"
libc = "0.2.73"
backtrace = { version = "0.3.44", optional = true }

arena = { path = "../arena", version = "0.0.0" }

[target.'cfg(target_os = "linux")'.dependencies]
perf-event = "0.4"

[features]
cpu_profiler = []

# Uncomment to enable for the whole crate graph
# default = [ "backtrace" ]
# default = [ "cpu_profiler" ]
