[package]
authors = ["The Rust Project Developers"]
name = "compiletest"
version = "0.0.0"
edition = "2018"

[dependencies]
diff = "0.1.10"
getopts = "0.2"
tracing = "0.1"
tracing-subscriber = { version = "0.2.13", default-features = false, features = ["fmt", "env-filter", "smallvec", "parking_lot", "ansi"] }
regex = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rustfix = "0.5.0"
lazy_static = "1.0"
walkdir = "2"
glob = "0.3.0"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies]
miow = "0.3"
winapi = { version = "0.3", features = ["winerror"] }
