[package]
authors = ["Miri Team"]
description = "An experimental interpreter for Rust MIR (core driver)."
license = "MIT/Apache-2.0"
name = "miri"
repository = "https://github.com/rust-lang/miri"
version = "0.1.0"
default-run = "miri"
edition = "2018"

[lib]
test = true # we have unit tests
doctest = false # but no doc tests

[[bin]]
name = "miri"
test = false # we have no unit tests
doctest = false # and no doc tests

[[bin]]
name = "miri-rustc-tests"
test = false # we have no unit tests
doctest = false # and no doc tests
required-features = ["rustc_tests"]

[dependencies]
getrandom = { version = "0.2", features = ["std"] }
env_logger = "0.7.1"
log = "0.4"
shell-escape = "0.1.4"
hex = "0.4.0"
rand = "0.7"

# A noop dependency that changes in the Rust repository, it's a bit of a hack.
# See the `src/tools/rustc-workspace-hack/README.md` file in `rust-lang/rust`
# for more information.
rustc-workspace-hack = "1.0.0"

# Enable some feature flags that dev-dependencies need but dependencies
# do not.  This makes `./miri install` after `./miri build` faster.
[target."cfg(unix)".dependencies]
libc = "0.2"

[dev-dependencies]
compiletest_rs = { version = "0.5", features = ["tmp"] }
rustc_version = "0.2.3"
colored = "2"

[features]
rustc_tests = []
