[package]
authors = ["The Rust Project Developers"]
name = "rustc_hir"
version = "0.0.0"
edition = "2018"

[lib]
doctest = false

[dependencies]
rustc_target = { path = "../rustc_target" }
rustc_macros = { path = "../rustc_macros" }
rustc_data_structures = { path = "../rustc_data_structures" }
rustc_index = { path = "../rustc_index" }
rustc_span = { path = "../rustc_span" }
rustc_serialize = { path = "../rustc_serialize" }
rustc_ast = { path = "../rustc_ast" }
tracing = "0.1"
smallvec = { version = "1.0", features = ["union", "may_dangle"] }
