[package]
authors = ["The Rust Project Developers"]
name = "rustbook"
version = "0.1.0"
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
clap = "2.25.0"

[dependencies.mdbook]
version = "0.4.3"
default-features = false
features = ["search"]
