[package]
name = "hyper-rustls"
version = "0.17.0"
authors = ["Joseph Birr-Pixton <jpixton@gmail.com>"]
license = "Apache-2.0/ISC/MIT"
readme = "README.md"
description = "Rustls+hyper integration for pure rust HTTPS"
homepage = "https://github.com/ctz/hyper-rustls"
repository = "https://github.com/ctz/hyper-rustls"

[dependencies]
bytes = "0.4"
ct-logs = { version = "^0.6.0", optional = true }
futures = "^0.1.28"
hyper = { version = "0.12.14", default-features = false }
rustls = "0.16"
tokio-io = "0.1.1"
tokio-rustls = "^0.10.0"
webpki = "^0.21.0"
webpki-roots = { version = "^0.17.0", optional = true }

[dev-dependencies]
tokio = "0.1"
tokio-tcp = "0.1"

[features]
default = ["tokio-runtime"]
tokio-runtime = ["hyper/runtime", "ct-logs", "webpki-roots"]

[[example]]
name = "client"
path = "examples/client.rs"
required-features = ["tokio-runtime"]

[[example]]
name = "server"
path = "examples/server.rs"
required-features = ["tokio-runtime"]
